### ISSUE TITLE
https://ifcopenshell.org/ - SSL do not work - Error 502

### ISSUE THREAD

**Issue by Mannshoch** [IfcOpenShell/website#3] opened 2022-08-26 13:41 UTC
**_https_** ://ifcopenshell.org/ 

SSL do not work - Error 502

**Comment by Mannshoch** [comment] 2022-08-29 09:55
ping

**Comment by Mannshoch** [comment] 2022-08-29 13:45
Ping @aothms

**Comment by aothms** [comment] 2022-08-29 14:36
There are several redesign and rework attempts for the website. Tackling
ssl separately doesn't have highest priority.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op ma 29 aug. 2022 15:46 schreef Mannshoch ***@***.***>:

**Comment by Mannshoch** [comment] 2022-08-29 15:10
I got Feedback from Windows Users, that Microsoft Edge only show a 502. It seems this user could not open this website without ssl. Even they try to remove s from https in the URL.

**Comment by aothms** [comment] 2022-09-03 10:01
Can't reproduce that

![Uploading afbeelding.png…]()

**Comment by Mannshoch** [comment] 2022-09-03 18:52
His coworker has the same Problem. I assume there is a group policy that do that. Couldn't you get a Let's encrypt Certificate?

**Comment by Moult** [comment] 2024-05-07 05:42
Closing because https works now.

**Closed by Moult** 2024-05-07 05:42 UTC
